### PR TITLE
Just more stuff happening

### PR DESCRIPTION
**Pull request by stkent**
Merge after #10

### CODE REVIEW

**Comment by stkent** [comment]
did not fix one instance of this issue: http://pmd.sourceforge.net/snapshot/pmd-java/rules/java/design.html#AccessorClassGeneration not sure what the recommended resolution is? cc @btkelly

**Comment by btkelly** [comment]
Hey Stuuuuuu

**Comment by btkelly** [comment]
Hello Automation

**Comment by btkelly** [comment]
Hello

**Comment by btkelly** [comment]
Hello
Stu

**Comment by btkelly** [comment]
PMD Violations:
Viloation in  /Users/bobbake4/android/amplify/library/src/main/java/com/github/stkent/amplify/Question.java

**Comment by btkelly** [comment]
PMD Violations:
<b>File: </b>/com/github/stkent/amplify/Question.java

**Comment by btkelly** [comment]
PMD Violations:
<b>File: </b>com.github.stkent.amplify.Question.java

**Comment by btkelly** [comment]
PMD Violations:
----------------------------------
<b>Rule: </b>[AccessorClassGeneration]
<b>Class: </b>com.github.stkent.amplify.Question.java
<b>Line: </b>[88]

**Comment by btkelly** [comment]
PMD Violations:
----------------------------------
<b>Rule: </b> [AccessorClassGeneration] - Avoid instantiation through private constructors from outside of the constructors class.
<b>Class: </b>com.github.stkent.amplify.Question.java <b>Line: </b>[88]

**Comment by btkelly** [comment]
PMD Violations:
----------------------------------
<b>Violation: </b> [AccessorClassGeneration]
Avoid instantiation through private constructors from outside of the constructors class.
<b>Class: </b>com.github.stkent.amplify.Question.java <b>Line: </b>[88]

**Comment by btkelly** [comment]
PMD Violations:
----------------------------------
<b>Violation: </b> [AccessorClassGeneration]
<b>Class: </b>com.github.stkent.amplify.Question.java
 <b>Line: </b>[88]
Avoid instantiation through private constructors from outside of the constructors class.
Help: [http://pmd.sourceforge.net/snapshot/pmd-java/rules/java/design.html#AccessorClassGeneration]

**Comment by btkelly** [comment]
PMD Violations:
----------------------------------
<b>Violation: </b> AccessorClassGeneration
<b>Help: </b> http://pmd.sourceforge.net/snapshot/pmd-java/rules/java/design.html#AccessorClassGeneration
<b>Class: </b>com.github.stkent.amplify.Question.java
 <b>Line: </b>88
Avoid instantiation through private constructors from outside of the constructors class.

**Comment by btkelly** [comment]
PMD Violations:
----------------------------------
<b>Violation: </b> AccessorClassGeneration
<b>Help: </b> http://pmd.sourceforge.net/snapshot/pmd-java/rules/java/design.html#AccessorClassGeneration
<b>Class: </b>com.github.stkent.amplify.Question.java -  <b>Line: </b>88
Avoid instantiation through private constructors from outside of the constructors class.

**Comment by btkelly** [comment]
PMD Violations:
----------------------------------
<b>Violation: </b> AccessorClassGeneration
<b>Help: </b> http://pmd.sourceforge.net/snapshot/pmd-java/rules/java/design.html#AccessorClassGeneration
<b>Class: </b>com.github.stkent.amplify.Question.java -  <b>Line: </b>88
Avoid instantiation through private constructors from outside of the constructors class.

**Comment by btkelly** [comment]
PMD Violations:
----------------------------------
<b>Violation: </b> AccessorClassGeneration
<b>Help: </b> http://pmd.sourceforge.net/snapshot/pmd-java/rules/java/design.html#AccessorClassGeneration
<b>Class: </b>com.github.stkent.amplify.Question.java -  <b>Line: </b>88
Avoid instantiation through private constructors from outside of the constructors class.

**Pull request merged**
